"use client";
import pic from "@/public/images/QRCode.png";
import DashOtp from "../../../UI/Inputs/DashOtp";
import { Button } from "@headlessui/react";
import { useTwoFactorFormSlice } from "@/lib/store/dashSecurityTwoFactoreStore";
import Image from "next/image";

export default function AppCodeForm() {
  const { setStep } = useTwoFactorFormSlice();

  const clickHandler = () => {
    setStep("success");
  };
  return (
    <form className="sm:px-20">
      <div className=" text-fe-c-text-title font-semibold  mb-5 sm:mb-6 w-fit mx-auto">
        <p className="text-sm sm:text-base text-center">
          Set up two-step authentication
        </p>
        <p
          className="text-xs sm:text-sm 
        text-center w-fit mx-auto font-normal mt-4 sm:mt-5"
        >
          Scan the QR code with authenticator app. If you don’t have an app yet,
          we <br className="hidden sm:block" /> recommend installing Google
          Authenticator.
        </p>
        <div className="w-full flex justify-center items-center">
          <span
            style={{ WebkitTextFillColor: "transparent" }}
            className="underline text-xs sm:text-sm font-normal decoration-orange-600 mx-auto
          inline-block underline-offset-4  bg-clip-text bg-orange-grad-btn"
          >
            Learn More
          </span>
        </div>
      </div>
      <Image
        placeholder="blur"
        className="mx-auto mb-5 sm:mb-6"
        src={pic}
        alt="barcode"
      />
      <p
        className="text-xs sm:text-sm 
        text-center w-fit mx-auto font-normal mb-4 "
      >
        Can’t scan? Enter the code:
      </p>

      <div className=" font-semibold w-full mx-auto sm:w-[23.75rem]">
        <div className="pb-6 border-neutral-400/30 dark:border-neutral-200/60 border-b">
          <div
            className="bg-neutral-400/25 dark:bg-white/15 text-fe-c-text-title
          flex justify-between items-center gap-4 px-4 py-3 sm:px-5 sm:py-4 rounded-lg"
          >
            <span className="text-xs sm:text-sm font-semibold">
              74EGXZUSNL5FO65J
            </span>
            <Button className="gap-2 flex items-center justify-center text-fe-c-text-title">
              <svg width="17" height="17" viewBox="0 0 17 17" fill="none">
                <g clipPath="url(#clip0_344_1926)">
                  <path
                    d="M7.86246 16.1145H4.88746C2.11788 16.1145 0.885376 14.882 0.885376 12.1125V9.13746C0.885376 6.36788 2.11788 5.13538 4.88746 5.13538H7.86246C10.632 5.13538 11.8645 6.36788 11.8645 9.13746V12.1125C11.8645 14.882 10.632 16.1145 7.86246 16.1145ZM4.88746 6.19788C2.69163 6.19788 1.94788 6.94163 1.94788 9.13746V12.1125C1.94788 14.3083 2.69163 15.052 4.88746 15.052H7.86246C10.0583 15.052 10.802 14.3083 10.802 12.1125V9.13746C10.802 6.94163 10.0583 6.19788 7.86246 6.19788H4.88746Z"
                    className="fill-fe-c-text-title"
                  />
                  <path
                    d="M12.1125 11.8645H11.3333C11.0429 11.8645 10.802 11.6237 10.802 11.3333V9.13746C10.802 6.94163 10.0583 6.19788 7.86246 6.19788H5.66663C5.37621 6.19788 5.13538 5.95704 5.13538 5.66663V4.88746C5.13538 2.11788 6.36788 0.885376 9.13746 0.885376H12.1125C14.882 0.885376 16.1145 2.11788 16.1145 4.88746V7.86246C16.1145 10.632 14.882 11.8645 12.1125 11.8645ZM11.8645 10.802H12.1125C14.3083 10.802 15.052 10.0583 15.052 7.86246V4.88746C15.052 2.69163 14.3083 1.94788 12.1125 1.94788H9.13746C6.94163 1.94788 6.19788 2.69163 6.19788 4.88746V5.13538H7.86246C10.632 5.13538 11.8645 6.36788 11.8645 9.13746V10.802Z"
                    className="fill-fe-c-text-title"
                  />
                </g>
                <defs>
                  <clipPath id="clip0_344_1926">
                    <rect width="17" height="17" fill="white" />
                  </clipPath>
                </defs>
              </svg>
              <span className="text-xs">Copy</span>
            </Button>
          </div>
        </div>

        <p
          className="text-xs sm:text-sm 
        text-center w-fit mx-auto font-normal my-4 sm:my-5 "
        >
          Enter the code generated by the app:
        </p>

        <DashOtp />
        <Button
          onClick={clickHandler}
          className="bg-red-100 btn-hover dark:bg-red-200 mt-8 w-full flex justify-center items-center rounded-lg"
        >
          <span
            style={{ WebkitTextFillColor: "transparent" }}
            className=" py-3  px-1 bg-clip-text bg-orange-grad-btn"
          >
            Verify
          </span>
        </Button>
      </div>
    </form>
  );
}
