import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/modules/Header/Header";
import Footer from "./components/modules/Footer/Footer";
import Headersm from "./components/modules/Header/Headersm";
// import 'bootstrap-icons/font/bootstrap-icons.css'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Find Email",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#030014] text-white`}
      >
        <div className="hidden lg:flex">
          <Header></Header>
        </div>
        <div className="flex lg:hidden">
          <Headersm></Headersm>
        </div>
        <div className="">
          <div className="absolute top-0 right-0 w-full h-[calc(60%)] bg-gradient-to-b from-[#f80e1e75] to-transparent"></div>
          {/* f80e1e75 */}
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
