import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import "bootstrap-icons/font/bootstrap-icons.min.css";
const merriweather = localFont({
  src: "./fonts/Merriweather-Regular.ttf",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Find Email",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-[#030014] text-white`}>
        {children}
      </body>
    </html>
  );
}
