import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/modules/Header/Header";
import Footer from "./components/modules/Footer/Footer";
import Headersm from "./components/modules/Header/Headersm";

const merriweather = localFont({
  src: "./fonts/Merriweather-Regular.ttf",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Find Email",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-[#030014] text-white`}>
        <div className="hidden lg:flex">
          <Header></Header>
        </div>
        <div className="flex lg:hidden">
          <Headersm></Headersm>
        </div>
        <main className="">
          <div className="absolute top-0 right-0 w-full h-[calc(30%)] md:h-[calc(60%)] bg-gradient-to-b from-[#f80ed94a] to-transparent pointer-events-none"></div>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
